identifier: k2y6973774f58cn0
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: blog
homeFolder: D:\Development\private\nx-jefiozie
distFolder: dist/apps/blog
outDir: D:\Development\private\nx-jefiozie\dist\static
handle404: ''
allowErrorCollect: true
